#include "oto.h"

// const Rsvwords rsvwords[] = {
//     {"\n",        TcLF        },
//     {",",         TcComma     },
//     {":",         TcColon     },
//     {"[",         TcSqBrOpn   },
//     {"]",         TcSqBrCls   },
//     {"(",         TcBrOpn     },
//     {")",         TcBrCls     },
//     {"<-",        TcLArrow    },
//     {"->",        TcRArrow    },
//     {"=",         TcEqu       },
//     {"+",         TcPlus      },
//     {"-",         TcMinus     },
//     {"*",         TcAster     },
//     {"/",         TcSlash     },
//     {"%",         TcPerce     },
//     {"==",        TcEEq       },
//     {"!=",        TcNEq       },
//     {">",         TcGt        },
//     {"<",         TcLt        },
//     {">=",        TcGe        },
//     {"<=",        TcLe        },

//     {"begin",     TcBegin     },
//     {"end",       TcEnd       },
//     {"define",    TcDefine    },
//     {"if",        TcIf        },
//     {"elsif",     TcElsif     },
//     {"else",      TcElse      },
//     {"then",      TcThen      },
//     {"loop",      TcLoop      }, 
//     {"and",       TcAnd       },
//     {"or",        TcOr        },
//     {"not",       TcNot       },
//     {"func",      TcFunc      },
//     {"track",     TcTrack     },
//     {"filter",    TcFilter    },
//     {"oscil",     TcOscil     },
//     {"sound",     TcSound     },

//     {"print",     TcPrint     },
//     {"beep",      TcBeep      },
//     {"play",      TcPlay      },
//     {"note",      TcNote      },
//     {"mute",      TcMute      },
//     {"bpm",       TcBpm       },
//     {"printwav",  TcPrintwav  },
//     {"exportwav", TcExportwav },
//     {"importwav", TcImportwav },
//     {"defse",     TcDefse     },
//     {"spectrum",  TcSpectrum  },
//     {"setfs",     TcSetfs     },
//     {"midiin",    TcMidiin    },
//     {"midiout",   TcMidiout   },
//     {"exit",      TcExit      },
// };